### PR TITLE
Updating Recipes to use Tags

### PR DESCRIPTION
**Pull request by Dradon7**
For better mod compat, this basically changes the glass recipes and various others to use the tags "forge:ingots/silver" and "forge:ingots/lead." This means that other modded metals can be used in your recipes. The big thing that I didn't do was change the recipes for the storage blocks and nuggets. If there's two different kinds of lead in a modpack, it's probably best if you can craft all the different silver storage blocks. There are mods for unifying ores, and all you really have to do is write a datapack anyway, so I think users should opt in and not opt out.
Another thing that this PR does that might not be as great is that it lets you craft crystal glass using any "forge:glass" of the proper color. This means you should be able to craft crystal glass out of quark's glass anything else tagged properly. It doesn't let you craft crystal glass out of crystal glass, even though there'd be no point, because Oreganized crystal glass is only tagged in "forge:glass", and (for example) red crystal glass is not tagged "forge:glass/red."

### CODE REVIEW

**Comment by Dradon7** [comment]
Actually, I might make another PR that properly tags crystal glass

**Review by GL33P-0R4NG3 — APPROVED** [review]
approved

**Review by GL33P-0R4NG3 — CHANGES_REQUESTED** [review]
please we want it compatible only through ingots ores etc.. so please change the tag "forge:glass/black" back and this for all other glass

**Review by GL33P-0R4NG3 — APPROVED** [review]
approved

**Review by GL33P-0R4NG3 — APPROVED** [review]
also change the "tag": "forge:glass_panes/colorless" back as i said tags only with ingots

**Review by GL33P-0R4NG3 — CHANGES_REQUESTED** [review]
also change the "tag": "forge:glass_panes/colorless" back as i said tags only with ingots

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Review by GL33P-0R4NG3 — APPROVED** [review]

**Comment by GL33P-0R4NG3** [comment]
Closed due to duplicate PR

**Pull request closed without merging**
